### ISSUE TITLE
omdoc files created by repeated latexml calls may differ

### ISSUE THREAD

**Issue by cmaeder** [KWARC/LaTeXML#5]
Using the script from https://svn.kwarc.info/repos/MMT/src/stex-mmt/run-latexml.sh repeated runs over smglom sets (git@gl.mathhub.info:smglom/sets.git) produced different omdoc outputs (with different files sizes). From 149 files 10 to 75 files are not reproduce in the same way.

**Comment by cmaeder** [comment]
sometimes an `<omdoc:omtext>` element wraps an  `<omdoc:metadata>` element (with extended `xml:id` attributes) for the same .tex file.

**Comment by dginev** [comment]
My first reaction was that you may have found a bug with the LaTeXML daemonization in sTeX. That is unlikely, however, because your calls to LaTeXML aren't daemonized in:

```
exec ${LATEXML_BASE}/bin/latexmlc --profile smglom \
  --path=/var/data/localmh/sty $dir/${theory}.tex \
  --destination=$dir/${theory}.omdoc \
  --log=$dir/${theory}.ltxlog \
  --preamble=$repoDir/lib/pre.tex \
  --postamble=$repoDir/lib/post.tex
```

For now for me this is a bug with the way your calling latexml, until proven otherwise. Use the sTeX/MMT issue tracs for those.

**Comment by cmaeder** [comment]
What would be the proper call to produce identical omdocs?

**Comment by cmaeder** [comment]
Still, I'm calling latexml always in the same way and get different results!

**Comment by cmaeder** [comment]
If the omdoc output is not entirely determined by the (.tex) input what else introduces entropy into the transformation (and should this not be avoided)?

**Comment by dginev** [comment]
Again, these are sTeX questions until you have found a latexml bug.

 Also, please provide an offending example, so that someone can reproduce and investigate.

**Comment by cmaeder** [comment]
So you're saying that sTeX produces different output if called with the same input? How could I call sTeX manually to verify this? 

I could send you may different omdoc files, if that's of any help.

**Comment by cmaeder** [comment]
If we cannot reproduce the same .omdoc file for the same input, debugging problems in .tex files (displayed via .omdoc) becomes rather difficult. By chance a problem may be gone for a while or reappear simply be rebuilding omdoc files.

**Comment by cmaeder** [comment]
I understand that different date strings are in log files, but this can not explain a different element structure in .omdoc files.

**Comment by dginev** [comment]
Ok, I am not on my phone any longer, so I can give you an in-depth reply here.

1. LaTeXML is a deterministic tool, so getting different XML results on different output is almost always a bug. You could conceivably define your own binding that behaves in a random way, but barring that it shouldn't happen. I am very interested in finding and fixing such bugs in LaTeXML, so it would be awesome if you could report them.

2. At the same time, there is a "burden of proof" (or if you prefer "burden of debugging") that needs to be distributed fairly to people and projects. As a rule of thumb, the first place an issue should be opened is in the GitHub repository of the piece of code that generated the error. In your case that seems to be the stex-mmt repo, which is why I am suggesting the sTeX issues as host for this discussion and troubleshooting.

3. Similarly, I can dedicate only that much time for looking into LaTeXML fixes, and I can't afford to research your entire toolchain. The ideal LaTeXML bug report contains:

 - A minimal TeX snippet reproducing the problem
 - The exact latexml command that can reproduce the problem
 - A brief description of the example and issue

Until I have these, I can't really help you.

4. In those terms, if LaTeXML produces inconsistent output in a fancy deployment setting with MMT and sTeX, say in docker, that is first a problem of that deployment and only upon investigation it could become a problem of LaTeXML. Once it is clear LaTeXML is faulty, I'd be happy to fix things.

**Comment by dginev** [comment]
So once you get back to a LaTeXML issue, please discuss the exact diffs in the OMDoc, the exact source that caused them and the exact setup+command in which LaTeXML was run, otherwise we're arguing hypotheticals.

**Comment by cmaeder** [comment]
Can you log into neptune.eecs.jacobs-university.de? There in  `/var/data/localmh/MathHub/smglom/sets/source` I've called `time for i in *.tex; do run-latexml.sh $i; done >& log &`. Afterwards (20 minutes later) I've moved the resulting .omdoc (and .ltxlog) files to a new directory res1/omdoc. I've repeated the step and got new omdoc files in res2/omdoc.   `diff -r -q res1/omdoc/ res2/omdoc/ | wc` reported that 16 .omdoc files differed. 

I did the same on my (faster) machine and got 40 differing files when comparing pairwise three runs. 

My script "run-latexml.sh" is (much) faster if the option --expire=10 is added. Only then `latexmls` is used. (I suspected that this variant would explain the difference, but it does not on my machine.)

**Comment by dginev** [comment]
Nope, that's too much effort for me, sorry. I don't even have a Neptune account (and I don't want one at the moment). If you are seeing the difference without running latexmls, then it is quite likely you are hitting an sTeX issue. If you can pin down the diffs and the exact circumstances in which they occur, that is debuggable.

**Comment by cmaeder** [comment]
On my machine the following happens:

```
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6241 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6440 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6241 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6241 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6440 Apr 16 17:50 union.omdoc

```

The bigger version contains the additional `<omdoc:omtext>` wrapper element. (There are other differences in other files.)

**Comment by dginev** [comment]
So, are you asking me why one file has 6241 bytes and the other 6440?

**Comment by cmaeder** [comment]
Yes, despite the identical call.
